sql_ut_base_lib = library('sql_ut_base', 'OBJECT', 'test_sql_utils.h', 'test_sql_utils.cpp', 'optimizer/ob_mock_part_mgr.h', 'optimizer/test_optimizer_utils.h', 'optimizer/test_optimizer_utils.cpp')
# target_link_libraries(['sql_ut_base', 'PUBLIC', 'mockcontainer'])
# function(['sql_unittest', 'case'])
# ob_unittest(argv)
# target_link_libraries([case, 'PRIVATE', 'sql_ut_base'])
# endfunction()
subdir('optimizer')
subdir('common')
subdir('parser')
subdir('resolver')
subdir('code_generator')
subdir('plan_cache')
subdir('engine')
subdir('rewrite')
subdir('session')
subdir('module')
subdir('monitor')
subdir('dtl')
if 'OB_BUILD_CLOSE_MODULES'
  subdir('audit')
endif
