# function(['ob_unittest', 'case'])
if 'ARGC', 'EQUAL', '1'
  case_exe = executable(case, case, '.cpp')
else
  ARGV_exe = executable(argv)
endif
if 'case', 'MATCHES', '^test_.*'
  test(case, case)
  # set_tests_properties([case, 'PROPERTIES', 'TIMEOUT', '300'])
endif
# target_link_libraries([case, 'PRIVATE', '-Wl,--whole-archive', 'mock_di', '-Wl,--no-whole-archive', 'oceanbase', 'gtest', 'gmock', hyperscan_lib])
# target_include_directories([case, 'PRIVATE', cmake_current_source_dir, cmake_source_dir, '/unittest', cmake_source_dir, '/mittest', cmake_source_dir, '/deps/oblib/unittest'])
# endfunction()
# file(['COPY', '.', 'DESTINATION', '.', 'FILES_MATCHING', 'PATTERN', '*.test'])
# file(['COPY', '.', 'DESTINATION', '.', 'FILES_MATCHING', 'PATTERN', '*.sql'])
# file(['COPY', '.', 'DESTINATION', '.', 'FILES_MATCHING', 'PATTERN', '*.result'])
# file(['COPY', '.', 'DESTINATION', '.', 'FILES_MATCHING', 'PATTERN', '*.schema'])
# file(['COPY', '.', 'DESTINATION', '.', 'FILES_MATCHING', 'PATTERN', '*.cfg'])
# file(['COPY', '.', 'DESTINATION', '.', 'FILES_MATCHING', 'PATTERN', '*.sh'])
# file(['COPY', 'run_tests.sh', 'DESTINATION', '.'])
subdir('sql')
subdir('libobcdc')
subdir('backup')
subdir('archive')
subdir('logservice')
subdir('storage')
subdir('observer')
subdir('share')
subdir('lib')
subdir('rootserver')
subdir('tools')
subdir('data_dictionary')
subdir('logminer')
subdir('plugin')
