#sql_unittest(test_exec_context)
# sql_unittest('test_physical_plan')
# sql_unittest('test_sql_fixed_array')
# sql_unittest('test_bit_vector')
subdir('aggregate')
subdir('dml')
subdir('subquery')
subdir('expr')
subdir('set')
subdir('px')
subdir('basic')
subdir('sort')
subdir('join')
subdir('monitoring_dump')
subdir('load_data')
