#log_unittest(basic_archive)
#log_unittest(test_archive_task)
#log_unittest(test_archive_manage)
#log_unittest(test_archive_file_utils)
archive_test_srcs = ['basic_archive.cpp', 'fake_archive_piece_mgr.cpp']
archive_test_lib = library('archive_test', archive_test_srcs)
# target_include_directories(['archive_test', 'PUBLIC', cmake_source_dir, '/unittest', cmake_source_dir, '/mittest'])
# target_link_libraries(['archive_test', 'PUBLIC', 'oceanbase'])
# function(['ob_unittest_archive', 'case'])
# ob_unittest(argv)
# target_link_libraries([case, 'PRIVATE', 'gtest', 'gmock', 'archive_test', 'observer_test', 'oceanbase'])
# endfunction()
#ob_unittest_archive(test_archive_manage test_archive_manage.cpp)
# ob_unittest_archive(['test_archive_file_utils', 'test_archive_file_utils.cpp'])
# ob_unittest_archive(['test_restore_archive_log', 'test_restore_archive_log.cpp'])
#ob_unittest_archive(test_restore_mysql_proxy test_restore_mysql_proxy.cpp)
#ob_unittest_archive(test_restore_oracle_proxy test_restore_oracle_proxy.cpp)
