# add_definitions('-D__ERROR_CODE_PARSER_')
src_list = ['ob_error.cpp', 'os_errno.cpp', cmake_source_dir, '/src/share/ob_errno.cpp']
ob_error_exe = executable('ob_error', src_list)
oberror_lib = shared_library('oberror', src_list)
# include_directories([cmake_source_dir, '/', cmake_source_dir, '/src', cmake_source_dir, '/deps/oblib/src'])
